name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  http: ^1.5.0
  image_picker: ^1.2.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
